# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
NULL

#' @noRd
NULL

#' @noRd
NULL

#' @noRd
NULL

#' @noRd
NULL

#' @noRd
NULL

.countMatches_cpp <- function(inter) {
    .Call(`_mapi_countMatches_cpp`, inter)
}

.getValues_cpp <- function(cells, inter, weights, values) {
    .Call(`_mapi_getValues_cpp`, cells, inter, weights, values)
}

.parseInter_cpp <- function(cells, inter, weights, values) {
    .Call(`_mapi_parseInter_cpp`, cells, inter, weights, values)
}

.parseInterPerm_cpp <- function(cells, inter, weights, values) {
    .Call(`_mapi_parseInterPerm_cpp`, cells, inter, weights, values)
}

.mkP4st_cpp <- function(r, N, ecc) {
    .Call(`_mapi_mkP4st_cpp`, r, N, ecc)
}

.trilaterate_cpp <- function(p0lon, p0lat, p1lon, p1lat, gc0, gc1) {
    .Call(`_mapi_trilaterate_cpp`, p0lon, p0lat, p1lon, p1lat, gc0, gc1)
}

